# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
    
steps:
- script: 'echo $(python.version)'
  displayName: 'Command Line Script'
- script: 'echo $(python.version)'
  displayName: 'Command Line Script 2'
- script: 'echo $(python.version)'
  displayName: 'Command Line Script 3'