# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

strategy:

  matrix:
    Python27:
      python.version: '2.7'
    Python34:
      python.version: '3.4'
    Python35:
      python.version: '3.5'
    Python36:
      python.version: '3.6'
    Python37:
      python.version: '3.7'
    Docs:
      python.version: '3.6'
    TZ:
      python.version: '3.6'
    macOS:
      python.version: '3.6'
    Windows36:
      python.version: '3.6'
    PyPy:
      python.version: 'pypy2'
    PyPy3:
      python.version: 'pypy3'
    
steps:
- script: 'echo $(python.version)'
  displayName: 'Command Line Script'