# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
  - job: firsttestjob
    pool: 'Default'
    steps:
    - script: 'echo $(python.version)'
    displayName: 'Command Line Script'
  - job: secondtestjob
    displayName: displayforsecondtestjob
    pool: 'Default'
    steps:
    - script: 'echo $(python.version)'
      displayName: 'Command Line Script'